paoo::Game::Level::LevelBase
Connection paoo.Game.Level.LevelBase.c
Statement paoo.Game.Level.LevelBase.str
ResultSet paoo.Game.Level.LevelBase.resultSet
int paoo.Game.Level.LevelBase.level
List<Integer> paoo.Game.Level.LevelBase.types
List<Integer> paoo.Game.Level.LevelBase.xpos
List<Integer> paoo.Game.Level.LevelBase.ypos
paoo.Game.Level.LevelBase.LevelBase(int n)
void paoo.Game.Level.LevelBase.close()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
List<Integer> paoo.Game.Level.LevelBase.getTypes()
Referenced by paoo.Game.Level.LevelHandle.loadLevelFromSQL.
List<Integer> paoo.Game.Level.LevelBase.getXpos()
Referenced by paoo.Game.Level.LevelHandle.loadLevelFromSQL.
List<Integer> paoo.Game.Level.LevelBase.getYpos()
Referenced by paoo.Game.Level.LevelHandle.loadLevelFromSQL.
void paoo.Game.Level.LevelBase.changeLevel(int n)
Referenced by paoo.Game.Level.LevelHandle.setLevel.
void paoo.Game.Level.LevelBase.update()