paoo::Game::Font
java.awt.Font paoo.Game.Font.arial
java.awt.Font paoo.Game.Font.segoe
paoo.Game.Font.Font()
References paoo.Game.Font.setArial, paoo.Game.Font.setSegoe.
void paoo.Game.Font.render(String msg, Graphics g, int x, int y)
References paoo.Game.Font.getArial.
Referenced by paoo.Game.Game.render.
java.awt.Font paoo.Game.Font.getArial()
Referenced by paoo.Game.Font.render.
void paoo.Game.Font.setArial(java.awt.Font arial)
Referenced by paoo.Game.Font.Font.
java.awt.Font paoo.Game.Font.getSegoe()
void paoo.Game.Font.setSegoe(java.awt.Font segoe)
Referenced by paoo.Game.Font.Font.