paoo::Items::SpaceShip
int paoo.Items.SpaceShip.dx
int paoo.Items.SpaceShip.dy
List<Shoot> paoo.Items.SpaceShip.missiles
int paoo.Items.SpaceShip.nr_shoots
paoo.Items.SpaceShip.SpaceShip(int x, int y)
References paoo.Items.Item.x, paoo.Items.Item.y.
void paoo.Items.SpaceShip.move()
References paoo.Items.Item.x, paoo.Game.Map.BOARD_WIDTH, paoo.Items.Item.width, paoo.Items.Item.y, paoo.Game.Map.BOARD_HEIGHT, paoo.Items.Item.height, paoo.Items.Item.image.
void paoo.Items.SpaceShip.keyPressed(KeyEvent e)
References paoo.Items.SpaceShip.fire.
List<Shoot> paoo.Items.SpaceShip.getMissiles()
Referenced by paoo.Game.Game.restore, paoo.Game.Game.nextLvl, paoo.Game.Game.render.
synchronized void paoo.Items.SpaceShip.fire()
References paoo.Items.Item.x, paoo.Items.Item.width, paoo.Items.Item.y, paoo.Items.Item.height.
Referenced by paoo.Items.SpaceShip.keyPressed.
synchronized void paoo.Items.SpaceShip.regenerateAmu()
void paoo.Items.SpaceShip.updateImg(Image img)
References paoo.Items.Item.image.
void paoo.Items.SpaceShip.keyReleased(KeyEvent e)
int paoo.Items.SpaceShip.getNr_shoots()
void paoo.Items.SpaceShip.setNr_shoots(int n)
void paoo.Items.SpaceShip.initSpaceShip()