paoo::Items::Item
int paoo.Items.Item.x
Referenced by paoo.Items.Backgorund.Backgorund, paoo.Items.Backgorund.setXY, paoo.Items.Backgorund.move, paoo.Items.Bombs.Bombs, paoo.Items.Bombs.move, paoo.Items.EnemyMissile.EnemyMissile, paoo.Items.EnemyMissile.move, paoo.Items.Heart.Heart, paoo.Items.Item.Item, paoo.Items.Item.getX, paoo.Items.Item.getBounds, paoo.Items.Item.setX, paoo.Items.Missile.Missile, paoo.Items.Missile.move, paoo.Items.Shoot.Shoot, paoo.Items.Shoots.Shoots, paoo.Items.SpaceShip.SpaceShip, paoo.Items.SpaceShip.move, paoo.Items.SpaceShip.fire.
int paoo.Items.Item.y
Referenced by paoo.Items.Backgorund.Backgorund, paoo.Items.Backgorund.setXY, paoo.Items.Bombs.Bombs, paoo.Items.EnemyMissile.EnemyMissile, paoo.Items.Heart.Heart, paoo.Items.Item.Item, paoo.Items.Item.getY, paoo.Items.Item.getBounds, paoo.Items.Item.setY, paoo.Items.Missile.Missile, paoo.Items.Shoot.Shoot, paoo.Items.Shoots.Shoots, paoo.Items.SpaceShip.SpaceShip, paoo.Items.SpaceShip.move, paoo.Items.SpaceShip.fire.
int paoo.Items.Item.width
Referenced by paoo.Items.Item.getImageDimensions, paoo.Items.Item.getBounds, paoo.Items.SpaceShip.move, paoo.Items.SpaceShip.fire.
int paoo.Items.Item.height
Referenced by paoo.Items.Item.getImageDimensions, paoo.Items.Item.getBounds, paoo.Items.SpaceShip.move, paoo.Items.SpaceShip.fire.
boolean paoo.Items.Item.vis
Referenced by paoo.Items.Bombs.move, paoo.Items.EnemyMissile.move, paoo.Items.Item.Item, paoo.Items.Item.isVisible, paoo.Items.Item.setVisible, paoo.Items.Missile.move.
Image paoo.Items.Item.image
Referenced by paoo.Items.Backgorund.changeImage, paoo.Items.Item.getImageDimensions, paoo.Items.Item.loadImage, paoo.Items.Item.getImage, paoo.Items.SpaceShip.move, paoo.Items.SpaceShip.updateImg.
paoo.Items.Item.Item(int x, int y)
References paoo.Items.Item.x, paoo.Items.Item.y, paoo.Items.Item.vis.
Image paoo.Items.Item.getImage()
References paoo.Items.Item.image.
Referenced by paoo.Game.Game.render, paoo.Game.Level.LevelHandle.render.
int paoo.Items.Item.getX()
References paoo.Items.Item.x.
Referenced by paoo.Game.Game.render, paoo.Game.Level.LevelHandle.render.
int paoo.Items.Item.getY()
References paoo.Items.Item.y.
Referenced by paoo.Game.Game.render, paoo.Game.Level.LevelHandle.render.
boolean paoo.Items.Item.isVisible()
References paoo.Items.Item.vis.
Referenced by paoo.Game.Game.render.
void paoo.Items.Item.setVisible(Boolean visible)
References paoo.Items.Item.vis.
Referenced by paoo.Game.Game.restore, paoo.Game.Game.nextLvl.
Rectangle paoo.Items.Item.getBounds()
References paoo.Items.Item.x, paoo.Items.Item.y, paoo.Items.Item.width, paoo.Items.Item.height.
void paoo.Items.Item.tick()
void paoo.Items.Item.setX(int x)
References paoo.Items.Item.x.
Referenced by paoo.Game.Game.restore, paoo.Game.Game.nextLvl.
void paoo.Items.Item.setY(int y)
References paoo.Items.Item.y.
Referenced by paoo.Game.Game.restore, paoo.Game.Game.nextLvl.
void paoo.Items.Item.getImageDimensions()
References paoo.Items.Item.width, paoo.Items.Item.image, paoo.Items.Item.height.
Referenced by paoo.Items.Backgorund.Backgorund, paoo.Items.Heart.Heart, paoo.Items.Shoots.Shoots.
void paoo.Items.Item.loadImage(String imageName)
References paoo.Items.Item.image.
Referenced by paoo.Items.Backgorund.Backgorund, paoo.Items.Bombs.move, paoo.Items.Heart.Heart, paoo.Items.Shoots.Shoots.