paoo::Menu::Buttons::MyButton
int paoo.Menu.Buttons.MyButton.x
int paoo.Menu.Buttons.MyButton.y
int paoo.Menu.Buttons.MyButton.width
int paoo.Menu.Buttons.MyButton.height
Image paoo.Menu.Buttons.MyButton.image
paoo.Menu.Buttons.MyButton.MyButton(String imagine, int x, int y)
void paoo.Menu.Buttons.MyButton.render(Graphics g)
Referenced by paoo.Game.Game.render.
boolean paoo.Menu.Buttons.MyButton.isPressed(int xx, int yy)
Referenced by paoo.Game.Input.MouseInput.mouseClicked, paoo.Menu.MouseInput.mouseClicked.
void paoo.Menu.Buttons.MyButton.changeImage(String imagine)
Referenced by paoo.Menu.MouseInput.mouseClicked.
void paoo.Menu.Buttons.MyButton.changeLocation(int x, int y)
Referenced by paoo.Game.Game.render.