paoo::Game::BaseValues
Connection paoo.Game.BaseValues.c
Statement paoo.Game.BaseValues.str
int paoo.Game.BaseValues.level
int paoo.Game.BaseValues.difficulty
int paoo.Game.BaseValues.music
String paoo.Game.BaseValues.text
ResultSet paoo.Game.BaseValues.resultSet
paoo.Game.BaseValues.BaseValues()
void paoo.Game.BaseValues.close()
Referenced by paoo.Game.Input.MouseInput.mouseClicked, paoo.Menu.MouseInput.mouseClicked.
void paoo.Game.BaseValues.update()
Referenced by paoo.Game.BaseValues.getLevel, paoo.Game.BaseValues.getDifficulty, paoo.Game.BaseValues.getMusic, paoo.Game.BaseValues.getFile.
int paoo.Game.BaseValues.getLevel()
References paoo.Game.BaseValues.update.
Referenced by paoo.Game.Level.LevelHandle.LevelHandle.
int paoo.Game.BaseValues.getDifficulty()
References paoo.Game.BaseValues.update.
Referenced by paoo.Game.Level.LevelHandle.LevelHandle.
int paoo.Game.BaseValues.getMusic()
References paoo.Game.BaseValues.update.
Referenced by paoo.Game.Level.LevelHandle.LevelHandle.
String paoo.Game.BaseValues.getFile()
References paoo.Game.BaseValues.update.
Referenced by paoo.Game.Level.LevelHandle.LevelHandle.
void paoo.Game.BaseValues.setLevel(int n)
Referenced by paoo.Menu.Menu.loadSettings.
void paoo.Game.BaseValues.setMusic(boolean n)
Referenced by paoo.Menu.Menu.loadSettings.
void paoo.Game.BaseValues.setDifficulty(int n)
Referenced by paoo.Menu.Menu.loadSettings.