paoo::Game::Game
final int paoo.Game.Game.WIDTH
final int paoo.Game.Game.HEIGHT
final int paoo.Game.Game.SCALE
final String paoo.Game.Game.NAME
JFrame paoo.Game.Game.frame
MyButton paoo.Game.Game.quitButton
boolean paoo.Game.Game.changeLevel
boolean paoo.Game.Game.pause
boolean paoo.Game.Game.gameOver
boolean paoo.Game.Game.running
boolean paoo.Game.Game.win
int paoo.Game.Game.fps
int paoo.Game.Game.tps
int paoo.Game.Game.steps
InputHandle paoo.Game.Game.input
MouseInput paoo.Game.Game.mouse
WindowHandle paoo.Game.Game.window
int paoo.Game.Game.lives
java.util.List<Shoots> paoo.Game.Game.incercari
java.util.List<Heart> paoo.Game.Game.hearts
SpaceShip paoo.Game.Game.spaceShip
LevelHandle paoo.Game.Game.level
int paoo.Game.Game.score
int paoo.Game.Game.enemyesLeft
int paoo.Game.Game.nivel
boolean paoo.Game.Game.load
MyButton paoo.Game.Game.reloadButton
MyButton paoo.Game.Game.resumeButton
MyButton paoo.Game.Game.saveButton
int paoo.Game.Game.tickCount
Font paoo.Game.Game.font
Timer paoo.Game.Game.timer
int paoo.Game.Game.waitTime
static void paoo.Game.Game.setLoad(boolean p)
Referenced by paoo.Menu.MouseInput.mouseClicked.
static boolean paoo.Game.Game.getLoad()
static void paoo.Game.Game.setLives(int n)
static int paoo.Game.Game.getLives()
static synchronized void paoo.Game.Game.restore()
References paoo.Game.Level.LevelHandle.loadLevelFromSQL, paoo.Items.Item.setVisible, paoo.Items.Item.setX, paoo.Items.Item.setY, paoo.Items.SpaceShip.getMissiles, paoo.Game.Level.LevelHandle.getItems.
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
static synchronized void paoo.Game.Game.nextLvl()
References paoo.Game.Level.LevelHandle.getSbase, paoo.Game.ScoreBase.saveScore, paoo.Game.Level.LevelHandle.setLevel, paoo.Game.Level.LevelHandle.getItems, paoo.Items.Item.setVisible, paoo.Items.Item.setX, paoo.Items.Item.setY, paoo.Items.SpaceShip.getMissiles.
Referenced by paoo.Game.Game.render.
static boolean paoo.Game.Game.isRunning()
Referenced by paoo.Game.Game.run, paoo.Menu.MouseInput.mouseClicked.
static void paoo.Game.Game.setRunning(boolean running)
Referenced by paoo.Game.Game.start, paoo.Game.Game.stop.
static boolean paoo.Game.Game.isChangeLevel()
static void paoo.Game.Game.setChangeLevel(boolean changeLevel)
static boolean paoo.Game.Game.isPause()
Referenced by paoo.Game.Game.run, paoo.Game.Game.render, paoo.Game.Input.InputHandle.keyPressed, paoo.Game.Input.MouseInput.mouseClicked.
static void paoo.Game.Game.setPause(boolean p)
Referenced by paoo.Game.Input.InputHandle.keyPressed, paoo.Game.Input.MouseInput.mouseClicked, paoo.Game.Input.WindowHandle.windowDeactivated.
static void paoo.Game.Game.setGameOver(boolean o)
Referenced by paoo.Game.Input.InputHandle.keyPressed, paoo.Game.Input.MouseInput.mouseClicked.
static boolean paoo.Game.Game.isOver()
Referenced by paoo.Game.Game.run, paoo.Game.Game.render, paoo.Game.Input.InputHandle.keyPressed, paoo.Game.Input.MouseInput.mouseClicked.
static void paoo.Game.Game.setWin(boolean o)
static boolean paoo.Game.Game.getWin()
Referenced by paoo.Game.Game.run, paoo.Game.Game.render.
static InputHandle paoo.Game.Game.getInput()
static void paoo.Game.Game.setInput(InputHandle input)
static MouseInput paoo.Game.Game.getMouse()
static void paoo.Game.Game.setMouse(MouseInput mouse)
static SpaceShip paoo.Game.Game.getSpaceShip()
Referenced by paoo.Game.Input.InputHandle.keyPressed, paoo.Game.Input.InputHandle.keyReleased.
static JFrame paoo.Game.Game.getFrame()
static MyButton paoo.Game.Game.getQuitButton()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
static MyButton paoo.Game.Game.getReloadButton()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
static MyButton paoo.Game.Game.getResumeButton()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
static MyButton paoo.Game.Game.getSaveButton()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
static LevelHandle paoo.Game.Game.getLevelHandle()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
paoo.Game.Game.Game()
synchronized void paoo.Game.Game.start()
References paoo.Game.Game.setRunning.
Referenced by paoo.Menu.MouseInput.mouseClicked.
synchronized void paoo.Game.Game.stop()
References paoo.Game.Game.setRunning.
void paoo.Game.Game.run()
References paoo.Game.Game.isRunning, paoo.Game.Game.isPause, paoo.Game.Game.isOver, paoo.Game.Game.getWin, paoo.Game.Game.render.
void paoo.Game.Game.render()
Metoda asta sa o folosesti pentru componentele animate daca ai timp pentru ele
References paoo.Game.Game.getWin, paoo.Game.Game.isOver, paoo.Menu.Buttons.MyButton.changeLocation, paoo.Menu.Buttons.MyButton.render, paoo.Game.Game.isPause, paoo.Game.Level.LevelHandle.render, paoo.Items.Item.isVisible, paoo.Items.Item.getImage, paoo.Items.Item.getX, paoo.Items.Item.getY, paoo.Items.SpaceShip.getMissiles, paoo.Game.Font.render, paoo.Game.Level.LevelHandle.getItems, paoo.Game.Game.nextLvl.
Referenced by paoo.Game.Game.run.
int paoo.Game.Game.getTickCount()
void paoo.Game.Game.setTickCount(int tick)
void paoo.Game.Game.init()
functia care imi initializeaza componentele jocului
void paoo.Game.Game.updateSpaceShip()
void paoo.Game.Game.updateMissiles()
void paoo.Game.Game.updateEnemyes()
void paoo.Game.Game.checkCollisions()