paoo::Game::Level::LevelHandle
int paoo.Game.Level.LevelHandle.nrLevel
int paoo.Game.Level.LevelHandle.difficulty
boolean paoo.Game.Level.LevelHandle.enableMusic
String paoo.Game.Level.LevelHandle.saveFile
BaseValues paoo.Game.Level.LevelHandle.base
LevelBase paoo.Game.Level.LevelHandle.lbase
ScoreBase paoo.Game.Level.LevelHandle.sbase
List<Ship> paoo.Game.Level.LevelHandle.items
Backgorund paoo.Game.Level.LevelHandle.backgorund
paoo.Game.Level.LevelHandle.LevelHandle()
References paoo.Game.BaseValues.getLevel, paoo.Game.BaseValues.getDifficulty, paoo.Game.BaseValues.getFile, paoo.Game.BaseValues.getMusic.
void paoo.Game.Level.LevelHandle.render(Graphics g)
References paoo.Items.Backgorund.changeImage, paoo.Items.Item.getImage, paoo.Items.Item.getX, paoo.Items.Item.getY, paoo.Items.Ship.isVisible, paoo.Items.Ship.getImage, paoo.Items.Ship.getX, paoo.Items.Ship.getY, paoo.Items.Ship.getShoots.
Referenced by paoo.Game.Game.render.
void paoo.Game.Level.LevelHandle.saveLevelToFile()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
void paoo.Game.Level.LevelHandle.loadLevelFromFile()
References paoo.Game.Level.LevelHandle.loadLevelFromSQL, paoo.Game.Level.AbstractShipFactory.createShip.
void paoo.Game.Level.LevelHandle.loadLevelFromSQL()
References paoo.Game.Level.LevelBase.getTypes, paoo.Game.Level.LevelBase.getXpos, paoo.Game.Level.LevelBase.getYpos, paoo.Game.Level.AbstractShipFactory.createShip.
Referenced by paoo.Game.Game.restore, paoo.Game.Level.LevelHandle.loadLevelFromFile, paoo.Game.Level.LevelHandle.setLevel.
void paoo.Game.Level.LevelHandle.setLevel(int nr)
References paoo.Game.Level.LevelBase.changeLevel, paoo.Game.Level.LevelHandle.loadLevelFromSQL.
Referenced by paoo.Game.Game.nextLvl.
int paoo.Game.Level.LevelHandle.getLevel()
List<Ship> paoo.Game.Level.LevelHandle.getItems()
Referenced by paoo.Game.Game.restore, paoo.Game.Game.nextLvl, paoo.Game.Game.render.
LevelBase paoo.Game.Level.LevelHandle.getLbase()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
BaseValues paoo.Game.Level.LevelHandle.getBase()
Referenced by paoo.Game.Input.MouseInput.mouseClicked.
ScoreBase paoo.Game.Level.LevelHandle.getSbase()
Referenced by paoo.Game.Game.nextLvl.
void paoo.Game.Level.LevelHandle.setDifficulty()