paoo::Items::Ship
int paoo.Items.Ship.x
Referenced by paoo.Items.BigEnemy.BigEnemy, paoo.Items.BigEnemy.fire, paoo.Items.Ship.Ship, paoo.Items.Ship.getX, paoo.Items.Ship.getBounds, paoo.Items.Ship.setX, paoo.Items.SmallEnemy.SmallEnemy, paoo.Items.SmallEnemy.fire.
int paoo.Items.Ship.y
Referenced by paoo.Items.BigEnemy.BigEnemy, paoo.Items.BigEnemy.fire, paoo.Items.Ship.Ship, paoo.Items.Ship.getY, paoo.Items.Ship.getBounds, paoo.Items.Ship.setY, paoo.Items.SmallEnemy.SmallEnemy, paoo.Items.SmallEnemy.fire.
int paoo.Items.Ship.width
Referenced by paoo.Items.Ship.getImageDimensions, paoo.Items.Ship.getBounds.
int paoo.Items.Ship.height
Referenced by paoo.Items.BigEnemy.fire, paoo.Items.Ship.getImageDimensions, paoo.Items.Ship.getBounds, paoo.Items.SmallEnemy.fire.
boolean paoo.Items.Ship.vis
Referenced by paoo.Items.Ship.Ship, paoo.Items.Ship.isVisible, paoo.Items.Ship.setVisible.
Image paoo.Items.Ship.image
Referenced by paoo.Items.Ship.getImageDimensions, paoo.Items.Ship.loadImage, paoo.Items.Ship.getImage.
paoo.Items.Ship.Ship(int x, int y)
References paoo.Items.Ship.x, paoo.Items.Ship.y, paoo.Items.Ship.vis.
Image paoo.Items.Ship.getImage()
References paoo.Items.Ship.image.
Referenced by paoo.Game.Level.LevelHandle.render.
int paoo.Items.Ship.getX()
References paoo.Items.Ship.x.
Referenced by paoo.Game.Level.LevelHandle.render.
int paoo.Items.Ship.getY()
References paoo.Items.Ship.y.
Referenced by paoo.Game.Level.LevelHandle.render.
boolean paoo.Items.Ship.isVisible()
References paoo.Items.Ship.vis.
Referenced by paoo.Game.Level.LevelHandle.render.
void paoo.Items.Ship.setVisible(Boolean visible)
References paoo.Items.Ship.vis.
Rectangle paoo.Items.Ship.getBounds()
References paoo.Items.Ship.x, paoo.Items.Ship.y, paoo.Items.Ship.width, paoo.Items.Ship.height.
void paoo.Items.Ship.setX(int x)
References paoo.Items.Ship.x.
void paoo.Items.Ship.setY(int y)
References paoo.Items.Ship.y.
abstract void paoo.Items.Ship.increaseDifficulty(int n)
abstract void paoo.Items.Ship.fire()
abstract java.util.List<Shoot> paoo.Items.Ship.getShoots()
Referenced by paoo.Game.Level.LevelHandle.render.
void paoo.Items.Ship.getImageDimensions()
References paoo.Items.Ship.width, paoo.Items.Ship.image, paoo.Items.Ship.height.
Referenced by paoo.Items.BigEnemy.BigEnemy, paoo.Items.SmallEnemy.SmallEnemy.
void paoo.Items.Ship.loadImage(String imageName)
References paoo.Items.Ship.image.
Referenced by paoo.Items.BigEnemy.BigEnemy, paoo.Items.SmallEnemy.SmallEnemy.